//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 12:15:46 AM SAST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.interstellar.transport.discovery.co.za/Routes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package za.co.discovery.transport.interstellar.service.api.xsd;
